### ISSUE TITLE
Allow users to input matches

### ISSUE THREAD

**Issue by jeanbza** [jadekler/git-reactjs-pongboard#2]
Currently we only poll from racquet.io to populate our db. Allow users to input on this app too.

**Comment by jeanbza** [comment]
- Only visible after selecting a club
- Visible in the menu
- UI is form with two inputs and a save button
- When you hit save it:
  - Makes the save button a green check button
  - Shoots the data to a POST endpoint
  - Redirects you to the feed
- POST endpoint that receives data and stores in DB

**Comment by elainemckinley** [comment]
I'm finding that it's difficult to add new matches with our current clubs table, since selecting a club by its name requires the human-readable name and in the controller we only have the URI parameter name (Pivotal Denver vs pivotal-denver, for instance).

This can be solved with a regex, but that seems a bit sketchy. What do you think of adding a column to the clubs table to add that URI name?

**Comment by jeanbza** [comment]
@austinmckinley good point man. Maybe a simpler approach is to refactor the route to use a club id instead of a club name. That would make all your links and references a lot easier.

**Comment by jeanbza** [comment]
Snagging this for myself to get it out quickly - last of the high priority stuff :)

**Comment by jeanbza** [comment]
Front and backend working - able to input matches. Couple of things missing:
- Validate against blank data
- Insert row into feed immediately, so user doesn't have to do a page refresh

**Comment by jeanbza** [comment]
Front and backend working - able to input matches. Couple of things missing:
- Validate against blank data
- Insert row into feed immediately, so user doesn't have to do a page refresh
